apiVersion: v1
kind: Pod
metadata:
  name: baijan-ide-pod-123 # Replace with the actual userId
  labels:
    app: baijan-ide-pod-123 # Replace with the actual userId
spec:
  containers:
    - name: nodejs-container
      image: baijan/pod-ide:latest
      ports:
        - containerPort: 3000
      command:
        - node
        - /app/dist/main.js

---
apiVersion: v1
kind: Service
metadata:
  name: baijan-ide-pod-service-123 # Replace with the actual userId
spec:
  selector:
    app: baijan-ide-pod-123 # Replace with the actual userId
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
